server:
  port: 8002
spring:
  #profiles defined
  config:
    activate:
      on-profile: dev
    #database configuration
  datasource:
    url: jdbc:mysql://localhost:3306/carbonuser?characterEncoding=utf-8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: carbonuser
    password: Carbon@mysqlUser
  redis:
    port: 6379
    host: localhost
    database: 1
    password: Carbon@redis
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 500
  data:
    mongodb:
      database: carbonuser
      username: carbonuser
      password: Maple@user
      host: localhost
      port: 27017
      grid-fs-database: mongoFile
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 300MB
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
#mybatis configuration
mybatis:
  #  config-location: classpath:mybatis/mybatis-config.xml
  configuration:
    map-underscore-to-camel-case: true
  typeAliasesPackage: cn.carbonface.carbonuser.entity
  mapperLocations: classpath:mybatis/mapper/*.xml


logging:
  config: classpath:log4j/log4j2-info.yml
#  config: src/main/resources/log4j2-config.xml
#  level:
#    cn.jay.repository: trace

#swagger config
springfox:
  documentation:
    swagger-ui:
      enabled: true
jwt:
  # secret Key
  secret: JWTSecret,CarbonFace
  # HeaderKey
  tokenHeader: Authorization
  # Token head
  tokenPrefix: Bearer
  # expire time
  expiration: 3600
  # refresh time
  refreshTime: 7
  # no jwt need filter
  antMatchers: /login/**,/actuator/*,/actuator